package com.lukelast.ktoon.data1.test04

import com.lukelast.ktoon.data1.Runner
import kotlinx.serialization.Serializable

class Test04 : Runner() {
    override fun run() = doTest(employees)
}

@Serializable
data class Employee(
    val id: Int,
    val name: String,
    val email: String,
    val age: Int,
    val city: String,
    val status: String,
    val score: Int,
    val department: String,
    val manager: String,
    val startDate: String,
    val salary: Int,
    val verified: Boolean,
)

val employees =
    listOf(
        Employee(
            id = 1,
            name = "Alice Johnson",
            email = "alice@company.com",
            age = 30,
            city = "Boston",
            status = "active",
            score = 95,
            department = "Engineering",
            manager = "Sarah Chen",
            startDate = "2020-01-15",
            salary = 125000,
            verified = true,
        ),
        Employee(
            id = 2,
            name = "Bob Smith",
            email = "bob@company.com",
            age = 25,
            city = "NYC",
            status = "active",
            score = 88,
            department = "Design",
            manager = "Mike Davis",
            startDate = "2021-03-20",
            salary = 95000,
            verified = true,
        ),
        Employee(
            id = 3,
            name = "Charlie Brown",
            email = "charlie@company.com",
            age = 35,
            city = "San Francisco",
            status = "inactive",
            score = 72,
            department = "Engineering",
            manager = "Sarah Chen",
            startDate = "2019-06-10",
            salary = 135000,
            verified = false,
        ),
        Employee(
            id = 4,
            name = "Diana Prince",
            email = "diana@company.com",
            age = 28,
            city = "Seattle",
            status = "active",
            score = 91,
            department = "Product",
            manager = "Emma Wilson",
            startDate = "2020-09-01",
            salary = 110000,
            verified = true,
        ),
        Employee(
            id = 5,
            name = "Eve Adams",
            email = "eve@company.com",
            age = 32,
            city = "Austin",
            status = "active",
            score = 85,
            department = "Sales",
            manager = "John Martinez",
            startDate = "2021-01-15",
            salary = 105000,
            verified = true,
        ),
        Employee(
            id = 6,
            name = "Frank Miller",
            email = "frank@company.com",
            age = 29,
            city = "Denver",
            status = "active",
            score = 89,
            department = "Engineering",
            manager = "Sarah Chen",
            startDate = "2020-11-20",
            salary = 120000,
            verified = true,
        ),
        Employee(
            id = 7,
            name = "Grace Hopper",
            email = "grace@company.com",
            age = 31,
            city = "Portland",
            status = "active",
            score = 94,
            department = "Engineering",
            manager = "Sarah Chen",
            startDate = "2019-08-15",
            salary = 130000,
            verified = true,
        ),
        Employee(
            id = 8,
            name = "Henry Ford",
            email = "henry@company.com",
            age = 27,
            city = "Chicago",
            status = "active",
            score = 82,
            department = "Operations",
            manager = "Lisa Johnson",
            startDate = "2022-02-01",
            salary = 90000,
            verified = true,
        ),
    )
